Update 2-mac-sign-mix-x86-64-taproot-online.yaml

diff --git a/.github/workflows/2-mac-sign-mix-x86-64-taproot-online.yaml b/.github/workflows/2-mac-sign-mix-x86-64-taproot-online.yaml
--- a/.github/workflows/2-mac-sign-mix-x86-64-taproot-online.yaml
+++ b/.github/workflows/2-mac-sign-mix-x86-64-taproot-online.yaml
@@ -1,4 +1,4 @@
-name: 2-mac-sign-mix-x86-64-taproot-online
+name: 2-mac-sign-mix-x86-64-taproot
 
 on:
   push:
@@ -18,7 +18,7 @@ jobs:
       - name: Set compiler
         run: |
           #set -e
-          #sudo xcode-select --switch /Applications/Xcode_14.3.1.app
+          sudo xcode-select --switch /Applications/Xcode_14.3.1.app
           echo "export CC=gcc-14" >> ~/.bashrc
           echo "export CXX=g++-14" >> ~/.bashrc
           echo "export RANLIB=gcc-ranlib-14" >> ~/.bashrc
@@ -101,13 +101,13 @@ jobs:
         working-directory: ${{runner.workspace}}
         env:
           OPENSSL_ROOT_DIR: ${{runner.workspace}}/nunchuk-qt/contrib/libnunchuk/contrib/openssl/lib
-          APP_PATH: "${{runner.workspace}}/build/Nunchuk.app"
         shell: bash
         run: |
           set -e
           source ~/.bashrc
           export PATH="/usr/local/opt/qt@5/bin:$PATH"
           export LDFLAGS="$LDFLAGS -L/usr/local/opt/qt@5/lib -L/usr/local/opt/boost@1.81/lib -L/usr/local/opt/berkeley-db@4/lib"
+          export LDFLAGS="$LDFLAGS -static-libgcc -static-libstdc++"
           export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/qt@5/include -I/usr/local/opt/boost@1.81/include -I/usr/local/opt/berkeley-db@4/include -I$OPENSSL_ROOT_DIR/include"
           export BOOST_ROOT="/usr/local/opt/boost@1.81"
           cmake -E make_directory ${{runner.workspace}}/build
@@ -126,14 +126,10 @@ jobs:
           export BOOST_ROOT="/usr/local/opt/boost@1.81"
           find ${{runner.workspace}}/HWI-3.1.0/dist/ -name "*mac-x86_64.tar.gz" -exec mv {} ./ \;
           find ${{runner.workspace}} -name "*mac-x86_64.tar.gz" -exec tar -xf {} \;
-          #wget -c -q "https://github.com/bitcoin-core/HWI/releases/download/2.3.1/hwi-2.3.1-mac-x86_64.tar.gz" -O - | tar -xz
           find ${{runner.workspace}} -name "hwi"
           find ${{runner.workspace}} -name "nunchuk-qt.app"
-          # otool -L "$APP_PATH"
           
           mv hwi Nunchuk.app/Contents/MacOS/hwi
-          #mv nunchuk-qt.app/Contents/MacOS/nunchuk-qt nunchuk-qt.app/Contents/MacOS/Nunchuk
-          #mv nunchuk-qt.app Nunchuk.app
           find ${{runner.workspace}} -name "Nunchuk.app"
           macdeployqt ${{runner.workspace}}/build/Nunchuk.app -qmldir=${{runner.workspace}}/nunchuk-qt
 
@@ -148,49 +144,71 @@ jobs:
           APP_PATH: "${{runner.workspace}}/build/Nunchuk.app"
           ENTITLEMENTS: ${{runner.workspace}}/nunchuk-qt/entitlements.plist
         run: |
-          set -e
+          set -euo pipefail # Dừng script nếu lỗi, bảo vệ biến chưa khai báo
+      
           echo "Setting up keychain and certificate..."
       
-          # Step 1: Create and unlock keychain
-          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
+          # Step 1: Giải mã chứng chỉ và tạo keychain
+          echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12
           security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
           security default-keychain -s build.keychain
           security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
           security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
           security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
       
-          # Step 2: Codesign all components inside the app bundle
+          echo "Checking Developer ID"
+          security find-identity -v -p codesigning
+          
+          echo "$MACOS_CERTIFICATE_NAME"
+          
+          # Step 2: Ký các thành phần bên trong ứng dụng
           echo "Signing internal components..."
-          find "$APP_PATH" -type f \( -name "*.dylib" -o -name "*.so" -o -name "*.bundle" -o -name "*.plugin" \) -exec codesign --deep --force --verify --verbose --options runtime --timestamp -s "$MACOS_CERTIFICATE_NAME" --entitlements "$ENTITLEMENTS" {} \;
-      
-          # Step 3: Sign frameworks and Qt components
+          find "$APP_PATH" -type f \( -name "*.dylib" -o -name "*.so" -o -name "*.bundle" -o -name "*.plugin" \) -print0 | \
+            while IFS= read -r -d '' file; do
+              echo "$file" | tee /dev/stderr
+              codesign --remove-signature "$file"
+              codesign --deep --force --verify --verbose --options=runtime --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$file" -vvv
+            done
+            
+          # Step 3: Ký framework và Qt components
           echo "Signing frameworks and Qt components..."
-          find "$APP_PATH" -name "Qt*" -type f -exec codesign --deep --force --verify --verbose --options runtime --timestamp -s "$MACOS_CERTIFICATE_NAME" --entitlements "$ENTITLEMENTS" {} \;
-      
-          # Step 4: Sign main executable and other key components
+          find "$APP_PATH" -name "Qt*" -type f -print0 | \
+            while IFS= read -r -d '' file; do
+              echo "$file" | tee /dev/stderr
+              codesign --remove-signature "$file"
+              codesign --force --deep --verify --verbose --options=runtime --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$file" -vvv
+            done
+            
+          # Step 4: Ký ứng dụng và các tệp thực thi chính
           echo "Signing main executables and app bundle..."
-          codesign --force --deep --verify --verbose --options runtime --timestamp -s "$MACOS_CERTIFICATE_NAME" --entitlements "$ENTITLEMENTS" "${APP_PATH}/Contents/MacOS/hwi"
-          codesign --force --deep --verify --verbose --options runtime --timestamp -s "$MACOS_CERTIFICATE_NAME" --entitlements "$ENTITLEMENTS" "${APP_PATH}/Contents/MacOS/Nunchuk"
-          codesign --force --deep --verify --verbose --options runtime --timestamp -s "$MACOS_CERTIFICATE_NAME" --entitlements "$ENTITLEMENTS" "$APP_PATH"
-      
-          # Step 5: Verify codesigning
-          echo "Verifying codesigning integrity..."
-          codesign --verify --deep --strict --verbose=2 "$APP_PATH"
-          codesign -dv --verbose=4 "$APP_PATH"
-          # spctl -a -vvvv "$APP_PATH"
-          # otool -L "$APP_PATH"
+          MAIN_EXECUTABLES=("hwi" "Nunchuk")
+          for filename in "${MAIN_EXECUTABLES[@]}"; do
+            echo "Signing $filename"
+            codesign --force --deep --verify --verbose --options=runtime --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$APP_PATH/Contents/MacOS/$filename" -vvv
+          done
+          codesign --remove-signature "$APP_PATH"
+          codesign --force --deep --verify --verbose --options=runtime --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$APP_PATH" -vvv
 
+          # Tắt App Translocation
+          #xattr -rc "$APP_PATH"
+          #spctl --add "$APP_PATH"
+          
+          # Step 5: Validate signature
           echo "Verifying codesigning integrity -dvvvvv ..."
           codesign -dvvvvv "$APP_PATH"
-          echo "Verifying codesigning integrity... -vvv --deep --strict "
-          codesign -vvv --deep --strict "$APP_PATH"
+          echo "Verifying codesigning integrity... -vvvv --deep --strict "
+          codesign -vvvv --deep --strict "$APP_PATH"
 
           echo "Verifying codesigning entitlements... d --entitlements "
-          codesign -d --entitlements :- "$APP_PATH"
+          codesign -dvvvv --entitlements :- "$APP_PATH"
 
           echo "Check otool..."
           otool -L "$APP_PATH/Contents/MacOS/Nunchuk"
-
+      
+          # Step 6: Cleanup
+          echo "Cleaning up temporary files..."
+          rm -f certificate.p12
+      
       - name: Notarize app bundle
         working-directory: ${{runner.workspace}}/build
         env:
@@ -199,57 +217,49 @@ jobs:
           PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.IO_APPLE_APP_PASSWORD }}
           APP_PATH: "${{runner.workspace}}/build/Nunchuk.app"
         run: |
-          set -e
-          # Notarize App Bundle
-          # ===============================
+          set -euo pipefail # Dừng script nếu lỗi
+      
+          # Step 1: Tạo hồ sơ notarization
           echo "Creating notarization profile..."
           xcrun notarytool store-credentials "notarytool-profile" \
             --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" \
             --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" \
             --password "$PROD_MACOS_NOTARIZATION_PWD"
-          
-          # Đóng gói ứng dụng thành file ZIP
+      
+          # Step 2: Tạo file ZIP từ app bundle
           echo "Packaging the app bundle..."
-          zip_file="$APP_PATH/../notarization.zip"
+          zip_file="${{runner.workspace}}/build/notarization.zip"
           ditto -c -k --keepParent "$APP_PATH" "$zip_file"
-          
-          # Gửi app lên Apple Notary
+      
+          # Step 3: Gửi app bundle để notarization
           echo "Submitting app bundle for notarization..."
-          if ! xcrun notarytool submit "$zip_file" --keychain-profile "notarytool-profile" --wait; then
-            echo "Notarization failed! Check logs:"
-            xcrun notarytool log "$zip_file"
-            exit 1
-          fi
-          
-          # Staple notarization vào app bundle
+          xcrun notarytool submit "$zip_file" \
+            --keychain-profile "notarytool-profile" \
+            --wait --verbose
+      
+          # Step 4: Gắn notarization ticket vào app
           echo "Stapling notarization ticket to the app bundle..."
-          if ! xcrun stapler staple "$APP_PATH"; then
-            echo "Stapler validation failed!"
-            exit 1
-          fi
-          
-          # Xác thực stapler
+          xcrun stapler staple "$APP_PATH"
+      
+          # Step 5: Xác minh quá trình stapling
           echo "Validating the stapling..."
           xcrun stapler validate "$APP_PATH"
-          
-          # Gatekeeper verification
+      
+          # Step 6: Kiểm tra Gatekeeper
           echo "Performing Gatekeeper verification..."
           spctl -a -vvvv "$APP_PATH"
           spctl --assess --type exec --verbose=4 "$APP_PATH"
-          
-          # Đóng gói ứng dụng notarized
+      
+          # Step 7: Đóng gói app notarized vào ZIP cuối
           echo "Repackaging the notarized app bundle..."
-          final_package_dir="$APP_PATH/../nunchuk-mac-qt"
+          final_package_dir="${{runner.workspace}}/nunchuk-mac-qt"
           mkdir -p "$final_package_dir"
           cp -R "$APP_PATH" "$final_package_dir/"
-          final_zip="$APP_PATH/../nunchuk-mac-qt.zip"
+          final_zip="${{runner.workspace}}/build/nunchuk-mac-qt.zip"
           ditto -c -k --keepParent "$final_package_dir" "$final_zip"
-          
-          # Loại bỏ cờ quarantine
-          echo "Removing quarantine flags..."
-          xattr -r -d com.apple.quarantine "$final_zip"
-          
+      
           echo "Notarization and packaging complete!"
+     
       
       - name: Get the version
         id: get_version
