Update build-mac-cmake-release.yaml

diff --git a/.github/workflows/build-mac-cmake-release.yaml b/.github/workflows/build-mac-cmake-release.yaml
--- a/.github/workflows/build-mac-cmake-release.yaml
+++ b/.github/workflows/build-mac-cmake-release.yaml
@@ -137,6 +137,8 @@ jobs:
           
       - name: Deploy Dmg
         working-directory: ${{runner.workspace}}/build
+        env:
+          APP_PATH: "${{runner.workspace}}/build/Nunchuk.app"
         run: |
           set -e
           source ~/.bashrc
@@ -147,13 +149,13 @@ jobs:
 
           # check Nunchuk.app
           find ${{runner.workspace}} -name "Nunchuk.app"
-          macdeployqt ${{runner.workspace}}/build/Nunchuk.app -qmldir=${{runner.workspace}}/nunchuk-qt
+          macdeployqt $APP_PATH -qmldir=${{runner.workspace}}/nunchuk-qt
           
            # Copy hwi built above 
-          cp -R ${{runner.workspace}}/HWI-3.1.0/dist/hwi/* ${{runner.workspace}}/build/Nunchuk.app/Contents/MacOS/
+          cp -R ${{runner.workspace}}/HWI-3.1.0/dist/hwi/* $APP_PATH/Contents/MacOS/
           echo "check copy result"
-          ls -l ${{runner.workspace}}/build/Nunchuk.app/Contents/MacOS/
-          ls -l ${{runner.workspace}}/build/Nunchuk.app/Contents/MacOS/_internal
+          ls -l $APP_PATH/Contents/MacOS/
+          ls -l $APP_PATH/Contents/MacOS/_internal
 
       - name: Codesign app bundle
         working-directory: ${{runner.workspace}}/build
@@ -201,28 +203,26 @@ jobs:
             
           # Signing libraries in _internal/
           echo "Signing libraries in _internal"
-          find ${{runner.workspace}}/Nunchuk.app/Contents/MacOS/hwi/_internal -type f -exec codesign --remove-signature {} \;
-          find ${{runner.workspace}}/Nunchuk.app/Contents/MacOS/hwi/_internal -type f -exec codesign --force --verify --options=runtime --verbose --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" {} -vvv \;
+          find "$APP_PATH/Contents/MacOS/hwi/_internal" -type f -exec sh -c '
+            for file do
+              echo "Signing: $file"
+              codesign --remove-signature "$file" || true
+              codesign --force --deep --verify --options=runtime --verbose --timestamp \
+                --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$file" -vvv \
+                || { echo "Error signing $file"; exit 1; }
+              echo "Signed: $file"
+            done
+          ' sh {} +
 
           # Signing hwi
           echo "Signing hwi"
-          codesign --remove-signature "${{runner.workspace}}/Nunchuk.app/Contents/MacOS/hwi"
-          codesign --force --deep --verify --options=runtime --verbose --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$${{runner.workspace}}/Nunchuk.app/Contents/MacOS/hwi" -vvv
+          codesign --remove-signature "$APP_PATH/Contents/MacOS/hwi"
+          codesign --force --deep --verify --options=runtime --verbose --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$APP_PATH/Contents/MacOS/hwi" -vvv
 
           # Sign Nunchuk
           echo "Signing Nunchuk"
-          codesign --remove-signature "${{runner.workspace}}/Nunchuk.app/Contents/MacOS/Nunchuk"
-          codesign --force --deep --verify --options=runtime --verbose --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$${{runner.workspace}}/Nunchuk.app/Contents/MacOS/Nunchuk" -vvv
-
-          # Signing hwi Nunchuk
-          #MAIN_EXECUTABLES=("hwi" "Nunchuk")
-          #for filename in "${MAIN_EXECUTABLES[@]}"; do
-          # echo "Signing > $filename"
-          # codesign --remove-signature "$APP_PATH/Contents/MacOS/$filename"
-          # codesign --force --deep --verify --options=runtime --verbose --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$APP_PATH/Contents/MacOS/$filename" -vvv
-          # echo "Verifying codesigning $filename"
-          # codesign -vvvv --deep --strict "$APP_PATH/Contents/MacOS/$filename"
-          #done
+          codesign --remove-signature "$APP_PATH/Contents/MacOS/Nunchuk"
+          codesign --force --deep --verify --options=runtime --verbose --timestamp --entitlements "$ENTITLEMENTS" -s "$MACOS_CERTIFICATE_NAME" "$APP_PATH/Contents/MacOS/Nunchuk" -vvv
           
           # Step signing app bundle
           echo "Signing main executables and app bundle..."
