Update nunchuk-ubuntu-x86_64.yml

diff --git a/.github/workflows/nunchuk-ubuntu-x86_64.yml b/.github/workflows/nunchuk-ubuntu-x86_64.yml
--- a/.github/workflows/nunchuk-ubuntu-x86_64.yml
+++ b/.github/workflows/nunchuk-ubuntu-x86_64.yml
@@ -192,50 +192,59 @@ jobs:
           chmod +x $OUTPUT_DIR/AppDir/usr/bin/nunchuk-qt
           
           # Copy libstdc++
-          LIBSTDCXX_PATH=$(gcc --print-file-name=libstdc++.so.6)
-          if [ -f "$LIBSTDCXX_PATH" ]; then
-            echo "📌 Copying libstdc++ from $LIBSTDCXX_PATH"
-            cp -a "$LIBSTDCXX_PATH"* $OUTPUT_LIB/
-          else
-            echo "❌ libstdc++ not found!"
-            exit 1
-          fi
+          #LIBSTDCXX_PATH=$(gcc --print-file-name=libstdc++.so.6)
+          #if [ -f "$LIBSTDCXX_PATH" ]; then
+          #  echo "📌 Copying libstdc++ from $LIBSTDCXX_PATH"
+          #  cp -a "$LIBSTDCXX_PATH"* $OUTPUT_LIB/
+          #else
+          #  echo "❌ libstdc++ not found!"
+          #  exit 1
+          #fi
 
           # Copy libgcc
-          LIBGCC_PATH=$(gcc --print-file-name=libgcc_s.so.1)
-          if [ -f "$LIBGCC_PATH" ]; then
-            echo "📌 Copying libgcc from $LIBGCC_PATH"
-            cp -a "$LIBGCC_PATH"* $OUTPUT_LIB/
-          else
-            echo "❌ libgcc not found!"
-            exit 1
-          fi
+          #LIBGCC_PATH=$(gcc --print-file-name=libgcc_s.so.1)
+          #if [ -f "$LIBGCC_PATH" ]; then
+          #  echo "📌 Copying libgcc from $LIBGCC_PATH"
+          #  cp -a "$LIBGCC_PATH"* $OUTPUT_LIB/
+          #else
+          #  echo "❌ libgcc not found!"
+          #  exit 1
+          #fi
           
           # Copy libolm (đúng thư viện đã build)
-          LIBOLM_PATH=$(ldconfig -p | grep libolm.so | awk '{print $NF}' | head -n 1)
-          if [ -f "$LIBOLM_PATH" ]; then
-            echo "📌 Copying libolm from $LIBOLM_PATH"
-            cp -a "$LIBOLM_PATH"* $OUTPUT_LIB/
-          else
-            echo "❌ libolm not found!"
-            exit 1
-          fi
+          #LIBOLM_PATH=$(ldconfig -p | grep libolm.so | awk '{print $NF}' | head -n 1)
+          #if [ -f "$LIBOLM_PATH" ]; then
+          #  echo "📌 Copying libolm from $LIBOLM_PATH"
+          #  cp -a "$LIBOLM_PATH"* $OUTPUT_LIB/
+          #else
+          #  echo "❌ libolm not found!"
+          #  exit 1
+          #fi
 
           # Copy libqt5keychain (đúng thư viện đã build)
-          LIBKEYCHAIN_PATH=$(ldconfig -p | grep libqt5keychain.so | awk '{print $NF}' | head -n 1)
-          if [ -f "$LIBKEYCHAIN_PATH" ]; then
-            echo "📌 Copying libqt5keychain from $LIBKEYCHAIN_PATH"
-            cp -a "$LIBKEYCHAIN_PATH"* $OUTPUT_LIB/
-          else
-            echo "❌ libqt5keychain not found!"
-            exit 1
-          fi
+          #LIBKEYCHAIN_PATH=$(ldconfig -p | grep libqt5keychain.so | awk '{print $NF}' | head -n 1)
+          #if [ -f "$LIBKEYCHAIN_PATH" ]; then
+          #  echo "📌 Copying libqt5keychain from $LIBKEYCHAIN_PATH"
+          #  cp -a "$LIBKEYCHAIN_PATH"* $OUTPUT_LIB/
+          #else
+          #  echo "❌ libqt5keychain not found!"
+          #  exit 1
+          #fi
           
           # Copy logo
           #cp ${{ env.NUNCHUK_LOGO }} $OUTPUT_DIR/nunchuk-qt.png
+
+          # Copy libraries (except Qt)
+          ldd $OUTPUT_DIR/AppDir/usr/bin/nunchuk-qt | awk '{print $3}' | grep -v '^(' | while read lib; do
+              if [[ "$lib" != *"/libQt"* && "$lib" != *"/Qt"* ]]; then
+                  if [ -f "$lib" ]; then
+                      echo "📌 Copying $(basename "$lib") from $lib to $OUTPUT_DIR/AppDir/usr/lib/"
+                      cp -a "$lib" "$OUTPUT_DIR/AppDir/usr/lib/"
+                  fi
+              fi
+          done
           
-          export ARCH=x86_64
-          # Deploy bằng CQtDeployer
+          # Deploy with CQtDeployer
           cqtdeployer -bin $OUTPUT_DIR/AppDir/usr/bin/nunchuk-qt \
                       -qmake /usr/lib/qt5/bin/qmake \
                       -qmlDir ${{ runner.workspace }}/nunchuk-qt \
