Update nunchuk-ubuntu-x86_64.yaml

diff --git a/.github/workflows/nunchuk-ubuntu-x86_64.yaml b/.github/workflows/nunchuk-ubuntu-x86_64.yaml
--- a/.github/workflows/nunchuk-ubuntu-x86_64.yaml
+++ b/.github/workflows/nunchuk-ubuntu-x86_64.yaml
@@ -144,30 +144,30 @@ jobs:
           cp -r * ${{ runner.workspace }}/nunchuk-linux
           echo "Deployment completed."
 
-      - name: Create Debian package
-        working-directory: ${{ runner.workspace }}/nunchuk-linux
-        run: |
-          mkdir -p DEBIAN
-          cat <<EOF > DEBIAN/control
-          Package: nunchuk-qt
-          Version: 1.0
-          Section: base
-          Priority: optional
-          Architecture: amd64
-          Maintainer: Nunchuk Inc <contact@nunchuk.io>
-          Description: Nunchuk Qt application
-          EOF
+      #- name: Create Debian package
+      #  working-directory: ${{ runner.workspace }}/nunchuk-linux
+      #  run: |
+      #    mkdir -p DEBIAN
+      #    cat <<EOF > DEBIAN/control
+      #    Package: nunchuk-qt
+      #    Version: 1.0
+      #    Section: base
+      #    Priority: optional
+      #    Architecture: amd64
+      #    Maintainer: Nunchuk Inc <contact@nunchuk.io>
+      #    Description: Nunchuk Qt application
+      #    EOF
           
           # Kiểm tra tồn tại của nunchuk-qt
-          if [ ! -f ./nunchuk-qt ]; then
-            echo "Error: nunchuk-qt binary not found!"
-            exit 1
-          fi
+      #    if [ ! -f ./nunchuk-qt ]; then
+      #      echo "Error: nunchuk-qt binary not found!"
+      #     exit 1
+      #    fi
 
           # Chạy dpkg-shlibdeps đúng thư mục
-          dpkg-shlibdeps -O ./nunchuk-qt 2>/dev/null | tee -a DEBIAN/control
+      #    dpkg-shlibdeps -O ./nunchuk-qt 2>/dev/null | tee -a DEBIAN/control
 
-          dpkg-deb --build ${{ runner.workspace }}/nunchuk-linux nunchuk-qt.deb
+      #    dpkg-deb --build ${{ runner.workspace }}/nunchuk-linux nunchuk-qt.deb
 
       - name: Zip release package
         working-directory: ${{ runner.workspace }}
